name: google_map_integration
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  # For State Management (1)
  provider: ^6.0.3

  # For Google Map (2)
  google_maps_flutter: ^2.1.8

  # For getting current location (3)
  geolocator: ^8.2.1

  # For getting searched location long-lat (4)
  geocoding: ^2.0.4

  # For networking (5)
  http: ^0.13.4

  # For Internet Connection Status (6)
  internet_connection_checker: ^0.0.1+4

  # For UI (7)
  lottie: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/lottie/
    - assets/mapicons/
    - assets/images/
    - assets/readme/

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Italic.ttf
          style: italic
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-Light.ttf
          weight: 200
        - asset: assets/fonts/WorkSans-Thin.ttf
          weight: 300
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 400
        - asset: assets/fonts/WorkSans-ExtraLight.ttf
          weight: 100